pipeline:
  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: wintercircle/node-yarn
    dockerfile: node-6/Dockerfile
    when:
      branch: master
  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: wintercircle/node-yarn
    dockerfile: node-alpine-latest/Dockerfile
    tags: alpine
    when:
      branch: master
