pipeline:
  docker-latest:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: wintercircle/node-yarn
    dockerfile: node/Dockerfile
    tags: latest
    when:
      branch: master
  docker-testing:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: wintercircle/node-yarn
    dockerfile: node-chrome/Dockerfile
    tags: testing
    when:
      branch: master
  docker-alpine:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: wintercircle/node-yarn
    dockerfile: node-alpine-latest/Dockerfile
    tags: alpine
    when:
      branch: master
