FROM node:latest
RUN apt-get update && apt-get install -y libx11-xcb-dev libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libnspr4 libdbus-1-3 libxss1 libxrandr2 libasound2 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 
RUN npm install -g yarn

